# Full configuration: https://github.com/eko/FeedBundle
eko_feed:
    feeds:
        places:
            title:       'Places'
            description: 'Latest places'
            link:        'https://track-hub.com'
            encoding:    'utf-8'
            author:      'Vincent Composieux' # Only required for Atom feeds
