services:
  - docker

before_install:
    - docker build --tag=trackhub-web ./docker/web/

jobs:
  include:
    - stage: install
      name: Composer install
      script: docker run -v `pwd`:/var/www -t trackhub-web /bin/bash -c "composer install --prefer-dist"
    - script: docker run -v `pwd`:/var/www -t trackhub-web /bin/bash -c "yarn install"
      name: yarn install
    - script: docker run -v `pwd`:/var/www -t trackhub-web /bin/bash -c "cd ./tests/phpcs && composer install"
      name: phpcs install
    - stage: debug info
      script: docker run -v `pwd`:/var/www -t trackhub-web /bin/bash -c "php -v"
    - stage: run tests
      script: docker run -v `pwd`:/var/www -t trackhub-web /bin/bash -c "./vendor/bin/phpunit -c tests/phpunit/phpunit.xml --no-coverage"
    - script: docker run -v `pwd`:/var/www -t trackhub-web /bin/bash -c "./bin/console doctrine:mapping:info"
    - script: docker run -v `pwd`:/var/www -t trackhub-web /bin/bash -c "yarn encore dev"
    - script: docker run -v `pwd`:/var/www -t trackhub-web /bin/bash -c "cd ./tests/phpcs && ./vendor/bin/phpcs --standard=phpcs.xml"
    - stage: prod env tests
      script: docker run -v `pwd`:/var/www -t trackhub-web /bin/bash -c "yarn encore production"

stages:
  - install
  - debug info
  - run tests
  - prod env tests

notifications:
    on_success: never
    on_failure: never
    on_change: never
