dist: bionic
language: php
php:
  - 7.3

services:
  - docker

jobs:
  include:
    - stage: tests
      name: Tests inside docker
      script: >-
        docker build --tag=trackhub-web ./docker/web/ &&
        docker run -v `pwd`:/var/www -t trackhub-web /bin/bash -c "
          php -v &&
          composer install --prefer-dist &&
          yarn install &&
          ./vendor/bin/phpunit -c tests/phpunit/phpunit.xml --no-coverage
          ./bin/console doctrine:mapping:info &&
          yarn encore dev &&
          yarn encore production
        "
    - name: PHPCS tests
      script: >-
          cd ./tests/phpcs &&
          composer install &&
          ./vendor/bin/phpcs --standard=phpcs.xml

stages:
  - tests

notifications:
    on_success: never
    on_failure: never
    on_change: never
