dist: bionic
language: php
php:
  - 7.3

services:
  - docker

jobs:
  include:
    - stage: tests
      name: Tests inside docker
      script: >-
        docker build --tag=trackhub-web ./docker/web/ &&
        docker run -v `pwd`:/var/www -t trackhub-web /bin/bash -c "
          php -v &&
          composer install --prefer-dist &&
          ./bin/console doctrine:mapping:info &&
          ./vendor/bin/phpunit -c tests/phpunit/phpunit.xml --no-coverage
          yarn install &&
          yarn encore dev &&
          yarn encore production
        "
    - name: PHPCS tests
      script: >-
          cd ./tests/phpcs &&
          composer install &&
          ./vendor/bin/phpcs --standard=phpcs.xml
    - name: Seeders tests
      script: |
        ./run.sh & \
        /bin/bash -c "
          WEB_IP=""
          until nc -z $WEB_IP 80
          do
              echo 'Waiting for web server...'
              WEB_IP=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' track_web_1) && \
              sleep 3
          done
        " && \
        docker exec -it track_web_1 /bin/bash -c "
            cd script/migration &&
            composer install &&
            ./vendor/bin/phinx seed:run
        "

stages:
  - tests

notifications:
    on_success: never
    on_failure: never
    on_change: never
