services:
  - docker

before_install:
    - docker build --tag=trackhub-web ./docker/web/
script:
    - docker run -v `pwd`:/var/www -t trackhub-web /bin/bash -c "php -v"
    - docker run -v `pwd`:/var/www -t trackhub-web /bin/bash -c "composer install --prefer-dist"
    - docker run -v `pwd`:/var/www -t trackhub-web /bin/bash -c "./vendor/bin/phpunit -c tests/phpunit/phpunit.xml --no-coverage"
    - docker run -v `pwd`:/var/www -t trackhub-web /bin/bash -c "./bin/console doctrine:mapping:info"
    - docker run -v `pwd`:/var/www -t trackhub-web /bin/bash -c "cd ./tests/phpcs && composer install && ./vendor/bin/phpcs --standard=phpcs.xml"
    - docker run -v `pwd`:/var/www -t trackhub-web /bin/bash -c "yarn install"
    - docker run -v `pwd`:/var/www -t trackhub-web /bin/bash -c "yarn encore dev"
    - echo "Production env tests"
    - docker run -v `pwd`:/var/www -t trackhub-web /bin/bash -c "yarn encore production"

notifications:
    on_success: never
    on_failure: never
    on_change: never
