services:
  - docker

before_install:
    - docker build --tag=trackhub-web ./docker/web/

script:
    - docker run -u www-data -t trackhub-web /bin/bash -c "php -v && ls"
#    - composer install --prefer-dist
#    - ./vendor/bin/phpunit -c tests/phpunit/phpunit.xml --no-coverage
#    - ./bin/console doctrine:mapping:info
#    - cd ./tests/phpcs && composer install && ./vendor/bin/phpcs --standard=phpcs.xml

notifications:
    on_success: never
    on_failure: never
    on_change: never
