hwi_oauth_redirect:
  resource: "@HWIOAuthBundle/Resources/config/routing/redirect_41.xml"
  prefix:   /{_locale}/connect

hwi_oauth_connect:
  resource: "@HWIOAuthBundle/Resources/config/routing/connect_41.xml"
  prefix:   /{_locale}/connect

hwi_oauth_login:
  resource: "@HWIOAuthBundle/Resources/config/routing/login_41.xml"
  prefix:   /{_locale}/login

facebook_login:
  path: /{_locale}/login/check-facebook
