index:
  path: /
  controller: App\Controller\Home::home

gps-new:
  path: /gps/new
  controller: App\Controller\Gps::new

gps-view:
  path: /gps/view/{id}
  controller: App\Controller\Gps::view

gps-list:
  path: /gps/list/{neLat}/{neLon}/{swLat}/{swLon}/{size}
  defaults:
    size: 10
  controller: App\Controller\Home::find

gps-download:
  path: /gps/download/{id}
  controller: App\Controller\Gps::download

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
