indexWithoutLocale:
  path: /
  controller: App\Controller\Home::index

home:
  path: /{_locale}
  controller: App\Controller\Home::home
  requirements:
    _locale: en|bg

gps-new-version:
  path: /{_locale}/gps/new-version/{id}
  controller: App\Controller\Track::newVersion

gps-new:
  path: /{_locale}/gps/new
  controller: App\Controller\Track::new

track-new-image:
  path: /{_locale}/gps/add-image/{id}
  controller: App\Controller\Track\Image::addImage

track-image-thumbnail:
  path: /images/generated/tit/{maxWidth}/{maxHeight}/{year}/{trackId}/{imagePath}
  controller: App\Controller\Track\Image::generateThumbnail
  requirements:
    year: '\d+'
    maxWidth: '\d+'
    maxHeight: '\d+'

gps-view:
  path: /{_locale}/gps/view/{id}
  controller: App\Controller\Track::view

gps-rate:
  path: /{_locale}/gps/view/{id}/rate
  controller: App\Controller\Track::rate

gps-list:
  path: /{_locale}/gps/list/{neLat}/{neLon}/{swLat}/{swLon}/{size}
  defaults:
    size: 10
  controller: App\Controller\Home::find

app_track_edit:
  path: /{_locale}/gps/edit/{id}
  controller: App\Controller\Track::edit

app_track_download_batch:
  path: /{_locale}/gps/download-batch
  controller: App\Controller\Track::downloadBatch

gps-download:
  path: /{_locale}/gps/download/{id}
  controller: App\Controller\Track::download

app_logout:
  path: /logout

app_privacy_policy:
  path: /{_locale}/privacy-policy
  controller: App\Controller\SimpleContent::privacyPolicy

app_tos:
  path: /{_locale}/terms-of-service
  controller: App\Controller\SimpleContent::termsOfService

app_contacts:
  path: /{_locale}/contacts

app_cookie_policy:
  path: /{_locale}/cookie-policy
  controller: App\Controller\SimpleContent::cookiePolicy

app_sponsored_integration:
  path: /{_locale}/sponsored-integration

app_legal_bases:
  path: /{_locale}/legal-bases
  controller: App\Controller\SimpleContent::legalBases

app_user_terms:
  path: /{_locale}/user/terms
  controller: App\Controller\User::terms

app_user_download_personal_data:
  path: /{_locale}/user/personal-data-download
  controller: App\Controller\User::downloadPersonalData

app_places:
  path: /{_locale}/places
  controller: App\Controller\Place::index

app_place_new:
  path: /{_locale}/place/new
  controller: App\Controller\Place::new

app_place_edit:
  path: /{_locale}/place/edit/{id}
  controller: App\Controller\Place::edit

app_place_view:
  path: /{_locale}/place/view/{id}
  controller: App\Controller\Place::view

app_place_new_image:
  path: /{_locale}/place/image/new/{id}
  controller: App\Controller\Place\Image::addImage

place_image_thumbnail:
  path: /images/generated/place/{maxWidth}/{maxHeight}/{year}/{placeId}/{imagePath}
  controller: App\Controller\Place\Image::generateThumbnail
  requirements:
    year: '\d+'
    maxWidth: '\d+'
    maxHeight: '\d+'

app_states:
  path: /{_locale}/states
  controller: App\Controller\States::index