# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    track_images_directory: '%kernel.project_dir%/public/uploads/track_images'
    track_images_thumbnails_directory: '%kernel.project_dir%/public/images/generated/tit'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    app.oauth.provider:
        class: App\Security\Core\OAuthUserProvider
        arguments:
            - '@fos_user.user_manager'
            - facebook: facebookId
    app.user.force.terms:
        class: App\Event\Listener\User\Terms
        arguments: ['@security.token_storage']
        tags:
            - { name: kernel.event_listener, event: kernel.request }
    app.admin.track:
        class: App\Admin\TrackAdmin
        arguments: [~, App\Entity\Track, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: track, label: 'Track' }
    app.admin.user:
        class: App\Admin\UserAdmin
        arguments: [~, App\Entity\User\User, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: user, label: 'User' }

    App\Repository\TrackRepository:
        class: App\Repository\TrackRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - App\Entity\Track

    App\Repository\Track\SlugRepository:
        class: App\Repository\Track\SlugRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - App\Entity\Track\Slug
